[package]
name = "FlowDesk"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
tokio = { version = "1.44.1", features = ["full"] }
tokio-tungstenite = "0.26.2"
futures-util = "0.3.31"
url = "2.5.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
